aurelia-ui-toolkits/aurelia-materialize-bridge

build/tasks/build.js, build/tasks/serve.js, build/tasks/watch.js, package.json
closes https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/8
These changes did it for me, but it's your decision on which implementation to use of course
=> feat(source-maps): enable sourcemaps during dev

sample/src/samples/input/basic-use.html, sample/src/samples/input/basic-use.js, sample/src/samples/input/textarea.html, sample/src/samples/input/textarea.js, src/input/input.html, src/input/input.js
=> Added disabled bindable on md-input custom element

src/pagination/pagination.html, src/pagination/pagination.js
Issues:
1. If you go to [Pagination Options demo](http://aurelia-ui-toolkits.github.io/demo-materialize/#/samples/pagination/options) and change Number of pages to 100 and press show last button, active class is not added to number 100. Also observe that only 8 numbers show in the list.
2. If you set overallPageLinks in that demo-source to 10, and do a gulp watch, visiblePageLinks is set to 10 even after Number of pages is changed to 100. Pager on search form with 0 pages as default will not work without extra code.
=> Pagination and visible links

src/validation/validationRenderer.js
=> feat(validation): add error list to md-select

src/tooltip/tooltip.js
Sorry for pull spam. I didn't notice that we had to remove old tooltip before initiate new updated one. #281 
Example: Button with tooltip. Pressing button -> tooltip change in code -> old tooltip is left on screen.
=> chore(md-tooltip): remove tooltip before init

sample/src/installation/installation-requirejs.md
Version 0.17.1 added style for chip and range :+1:
=> docs(install): change bridge bundle resources

src/exports.js
In the dark of the night, `build-index-remove` tags in `exports.js`, run deep into the woods and got lost. I found them and followed them safe back.
=> fix(typescript): cannot find module errors during compile

sample/src/samples/datepicker/registry.json, sample/src/samples/datepicker/validation.html, sample/src/samples/datepicker/validation.js, sample/src/samples/input/aurelia-validation.html, sample/src/samples/input/aurelia-validation.js, src/datepicker/datepicker.js, src/validation/validationRenderer.js
I have made some modification for displaying the error on `textarea` and `datepicker` elements with `aurelia-validation`, which I need in my app. I have also update the sample app with some example for the `select`, `textarea` and `datepicker` elements.
The only problem I get is that the datepicker error doesn't add/remove when changing the value, but only if we click again on the input field or if we trigger the validation manually. But I think that is a problem on the way the value is changed on a datepicker because it doesn't trigger the `render` function of the `ValidationRenderer` when changing the value.
=> Add validation for textarea and datepicker. Update the sample app.

src/progress/progress.js
md-pixel-size was not working if set to a static value or set before the attached event.  It was only working as used in the sample but didn't work as it would typically be used.
Also, let mdSize remain set when mdPixelSize is set.  mdPixelSize overrides mdSize due to inline styles having higher priority.
=> fix(md-progress): set md-pixel-size on attached

sample/src/samples/select/validation.html, sample/src/samples/select/validation.js, src/validation/validationRenderer.js
I have added an example on the validation of a select because when an error is displayed under a select and then we change the value dynamically, the error was not removed, even after a reset, and cause some weird displaying of the label.
I have made two commits, one to add the example in the `sample` solution and one that fix the bug in the `validationRenderer`
=> refactor(validation) remove the md-select error in all cases

src/range/range.html
I think this would be better, because there are defintely use cases where one wants to change the range min, max etc. values.
However, i'm not familiar with your "goales", so it might be that you want to reject this and encourage people to use the range input directly without AMB, if they have such a use case.
=> Change range to one-way instead of one-time

src/validation/validationRenderer.js
When a form is loaded and you start editing an input making it valid straightaway it is not reflected on the input.
This is because renderer ignores valid validation results and there are no invalid results to be removed which would normally add `valid` class.
By moving setting `valid` and `invalid` classes to a separate cycle we will make sure that correct validation status will always be applied to the input.
=> Update renderer to properly show validation result

.vscode/settings.json, jsconfig.json, sample/src/shared/components.json, src/collapsible/collapsible.js
Main work here is surfacing the open/close events from the Materialize collapsible component in friendly ways for the Aurelia developer. The developer can hook these events in one of two ways:
1. Using the `.call` expression in the attribute to directly bind a function call on their view model via the new `onOpen` and `onClose` properties (note: `on-open` and `on-close` in attribute syntax!).
2. Via the `EventAggregator` infrastructure where two new events are published in the form of: `aurelia-md-bridge:collapsible:[open|close]`. I would especially like feedback on whether or not you guys want the framework to be publishing via `EventAggregator` and, if so, if you "like" the naming scheme I've chosen.
*NOTE:* this also adds a new sample for the Collapsible component from [this …
=> Add collapsible open/close events

sample/src/shared/components.json, src/badge/badge.js
Adds support for custom captions to the Badge component which was called out in #108.
Also fixes issue where the `is-new` property, while bindable in the static "one-time" sense, would not dynamically reflect changes to the bound property because there was no handling of the binding change event to add/remove the CSS `new` class.
=> Add custom caption support for the Badge component

src/select/select.js
When a select is reattached after being hidden with `if.bind` a duplicate label is created
=> fix(select): Do not create duplicate label

src/select/select.js
If not removed those `div`s get reattached to the DOM, stay there unreferenced, and interfere with the lable
=> fix(select): remove validation errors on detached

src/select/select.js
Materialize cannot clean up this UL on `destroy` because it's already removed from DOM by Aurelia
=> fix(select): remove orphaned UL

src/validation/validationRenderer.js
Search for validation messages in the correct input parent. Current implementation does not underline invalid SELECT
=> fix(validation): use correct parent

src/validation/validationRenderer.js
Green/red border should be removed when a validation message is unrendered. This normally happens when an element is hidden.
Also, fix typo in underlining a generic `input`
=> fix(validation): remove border on unrender

src/colors/md-colors.html
The style was overriding the previous declaration
=> fix(colors): color for `.btn-floating.error:hover`

src/autocomplete/autocomplete.js
Adds support for providing minLength and limit attributes for AutoComplete - see http://materializecss.com/forms.html
=> Add support for minLength and limit in AutoComplete

src/chip/chips.js
The binding for using autocomplete in Chips has changed: http://materializecss.com/chips.html. Allowing autocompleteOptions to be passed also makes it possible to control autocomplete limit and minLength.
=> feat(md-chips): Fixed broken autocomplete binding

src/select/select.js, src/validation/validationRenderer.js
This will make labelling and validation consistent.
Validator is also modified to reflect the changes to `select`.
=> fix(select): Always wrap `select` with `.input-field`

package.json
I removed the peerDependencies completely, because it's still optional to use materialize-css or github:Dogfalo/materialize.
That fixes https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/438
=> Removed peerDependencies completely

src/select/select.js
it works by removing event handlers which trigger the popup
=> feat(select): add readonly

src/tabs/tabs.js
to fire the custom tabSelected event
=> fix(md-tabs): reset click event in refresh method to allow dynamically added tabs

src/datepicker/datepicker.js
When a datepicker is editable and the value is entered manually the calendar is not open.
So, pressing enter or tab and sending the `close` command does not trigger the `onClose` handler which is supposed to update the value.
Hence, the need to update it explicitly.
=> fix(datepicker): update bound value on keyDown

src/select/select.js
Plus, readonly did not work because of the missing code
=> fix(select): restore validation state after refresh

src/colors/md-colors.html
Fix a typo that was overriding the normal .btn-floating:focus style
=> fix(colors): color for `btn-floating.error:focus`

src/input/input.html, src/input/input.js
Basic html input attribute maxlength was missing from the binding
=> feat(input): add maxlength attribute for input and textarea

src/autocomplete/autocomplete.ts
I'm firing a change event for onAutocomplete to fix the problem that I was having with using the keyboard to select something from the dropdown and the change event not firing. 
Fixes #514 
This is just for non-v1, and probably would be good to add it here as well if the PR is accepted: https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/blob/v1/src/autocomplete/autocomplete.ts#L44
=> onAutocomplete firing a change event for non-v1

src/radio/radio.html
The `!model` check falsely presumed that a `model.bind="false"` meant binding to the value attribute. This in turn binds the string value `"false"` instead of the boolean `false`. Aurelia's own documentation recommends binding boolean values with the `model.bind="false"` syntax. ref: https://aurelia.io/docs/binding/radios#booleans.
Though this could be considered a patch fix to match expected behaviour in Aurelia, apps in the wild may depend on the existing behaviour. It may therefore be worth considering making this a major bump due to breaking change.
=> fix(radio): allow model binding with boolean value 'false'

src/lookup/lookup.ts
- Add open() on element focus.
- Add onBlur behaviour options: Enables setting the underlying value if the user blurs the element and the filter is a match with a single option. Also enables the clearing of the filter and value if the current filter matches no options.
Monkey tested.
=> Add lookup tweaks
