- build/tasks/build.js
- build/tasks/prepare-release.js
- src/index.js
> Added remove tags in build for definition file

- src/colors/md-colors.html
tested on Firefox and Chrome
close #176
> fix(md-range): set theme color on thumb

- sample/src/samples/input/placeholder.html
- sample/src/samples/input/placeholder.js
- sample/src/samples/input/registry.json
- src/input/input.js
also add sample for input using md-placeholder attribute
> fix(md-input): remove update error for md-placeholder

- sample/src/help/docs/app-developers-tutorials/setup.md
as title, we add instructions about how to remove bootstrap from app skeleton
> improve docs: explain bootstrap removal #185

- sample/src/samples/pagination/options.html
- sample/src/samples/pagination/options.js
- src/pagination/pagination.html
- src/pagination/pagination.js
Added option to show / hide individual page links.
Show only so many individual page links. Don't fill the screen when there are lots of pages.
> Pagination improvements

- sample/config.js
- sample/src/samples/pagination/options.js
- src/pagination/pagination.js
Two fixes to pagination.
1, Fix bug where decimal numbers were shown in the links. This occured when the numer of links were an odd number.
2, Update the links when mdPages changed.
> Pagination fixes

- src/select/select.js
This make the md-select component forward blur event. For validation errors you also need the changes in validationRenderer #250
> feat(md-select): forward blur events

- src/input/input.js
> chore(md-input): remove aurelia-pal dependency

- src/select/select.js
> chore(md-select): delay blur event

- sample/src/samples/input/aurelia-validation.html
- sample/src/samples/input/aurelia-validation.js
- src/input/input.js
- src/validation/validationRenderer.js
> feat(md-input): add md-show-errortext attribute

- sample/src/samples/select/basic-use.html
- sample/src/samples/select/basic-use.js
- sample/src/samples/select/registry.json
- src/select/select.js
> fix(md-select): fire blur after dropdown hides

- .gitignore
- package.json
> chore(package): aurelia-pal dependency

- sample/src/samples/select/validation.html
- sample/src/samples/select/validation.js
- src/select/select.js
- src/validation/validationRenderer.js
md-select="show-errortext: false; label: ...
default true
> feat(md-select): show-errortext option

- sample/src/samples/collections/avatar.html
- src/colors/md-colors.html
> feat(md-collection): invert theme color for avatar

- src/tooltip/tooltip.js
Issue:
- Loading data from server and change tooltip doesn't update tooltip text.
Related? #266
> fix(md-tooltip): update tooltip when tooltip text change

- .editorconfig
This is option 2 for fixing #351.
> Remove end_of_line setting from .editorconfig

- src/select/select.js
Injecting it causes an exception with Jspm 0.17.40 + SystemJs 0.20.9
> fix(select): do not inject LogManager

- src/card/card.html
> fix(md-card): change condition to show title

- src/colors/md-colors.html
Without these hovering and focusing changes a button color to primary
> fix(colors): Add error button styles

- src/char-counter/char-counter.js
md-char-counter should be able to be applied to textarea elements as well as input element.
Fixes Issue #404.
> Fix(char-counter): add support for textarea elements

- src/file/file.html
- src/file/file.js
- src/range/range.html
- src/range/range.js
Here is a new PR of https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/pull/426 for adding md-readonly to md-range and md-file.
> fix(md-range, md-file): add md-readonly

- src/card/card.html
- src/card/card.js
Add the card-action block and the option sticky-action
> feat(md-card): add action

- src/checkbox/checkbox.html
- src/checkbox/checkbox.js
It works by immediately reverting the change
> feat(checkbox): implement readonly

- src/dropdown/dropdown-element.js
- src/dropdown/dropdown.js
Same PR as #457  but with correct naming convention and only one commit.
Fix the issue #451
> feat(md-dropdown): add stopPropagation option

- src/card/card.html
Correct sticky-action location
> fix(md-card): Set sticky-action on correct div

- src/card/card.html
- src/card/card.js
>  feat(md-card): add md-class

- src/checkbox/checkbox.js
fixes https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/485
> fix(checkbox): check for null reference

- src/timepicker/timepicker.ts
Changed the controlId for TimePicker from "md-datepicker" to "md-timepicker".
> Fixed TimePicker controlId

- README.md
Remove accidental repeated word.
> doc(all): Fix repeated word typo in README.md
